feature: added item to item recommendation algorithm
smdka/java-filmorate pull request #16
Opened 2023-01-25 16:28 UTC by neobelov

2023-01-26 17:30 UTC, smdka commented on src/main/java/ru/yandex/practicum/filmorate/controller/UsersController.java
> +        return filmService.getRecommendations(id);
Все-таки, я думаю уместнее использовать userService, а уже в userService подключить filmDbStorage

2023-01-27 10:16 UTC, neobelov commented on src/main/java/ru/yandex/practicum/filmorate/controller/UsersController.java
> +        return filmService.getRecommendations(id);
Сделал:)

2023-01-27 13:00 UTC, smdka commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +                stringBuilder.append(film_id + ", ");
Лучше не создавать в цикле объекты String, а использовать append().append()

2023-01-27 13:00 UTC, smdka commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +            return List.of();
Collections.emptyList() было бы понятнее

2023-01-27 13:00 UTC, smdka commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +                List<Integer> user_ids = converter.convert(rs.getArray("user_ids"));
для переменных лучше использовать lowerCamelCase

2023-01-27 13:00 UTC, smdka commented on src/main/java/ru/yandex/practicum/filmorate/utilities/recommendations/Matrix.java
> +            return null;
return Optional.empty()

2023-01-27 13:00 UTC, smdka commented on src/main/java/ru/yandex/practicum/filmorate/utilities/recommendations/Matrix.java
> +        }
Можно проще: return rows.isEmpty() && columns.isEmpty();

2023-01-27 13:00 UTC, smdka commented on src/main/java/ru/yandex/practicum/filmorate/utilities/recommendations/Recommender.java
> +            return List.of();
Collections.emptyList() было бы понятнее

2023-01-27 13:00 UTC, smdka commented on src/main/java/ru/yandex/practicum/filmorate/utilities/recommendations/Recommender.java
> +    public static Matrix generateTestMatrix() {
Метод не используется

2023-01-27 13:04 UTC, neobelov commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +                stringBuilder.append(film_id + ", ");
Не понял, как это сделать:) сколько будет рекомендаций, нельзя предсказать) объясни, пожалуйста, что имеешь в виду

2023-01-27 13:05 UTC, neobelov commented on src/main/java/ru/yandex/practicum/filmorate/utilities/recommendations/Matrix.java
> +            return null;
У меня есть разница в таблице между optional.empty и между null. Null значит, что в таблице в этой позиции вообще ничего нет. Empty, что для фильма этот пользователь не поставил оценку

2023-01-27 13:06 UTC, smdka commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +                stringBuilder.append(film_id + ", ");
stringBuilder.append(film_id).append(",')
Кроме того, имена переменных должны быть в lowerCamelCase

2023-01-27 13:06 UTC, neobelov commented on src/main/java/ru/yandex/practicum/filmorate/utilities/recommendations/Recommender.java
> +    public static Matrix generateTestMatrix() {
Пока оставил, это перенесу в тест

2023-01-27 13:07 UTC, neobelov commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +                stringBuilder.append(film_id + ", ");
Принял, спасибо

2023-01-27 13:08 UTC, neobelov commented on src/main/java/ru/yandex/practicum/filmorate/utilities/recommendations/Matrix.java
> +            return null;
То есть,null нам показывает, что нет такого фильма и/или такого пользователя

2023-01-27 13:49 UTC, neobelov commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +            return List.of();
Принято

2023-01-27 13:52 UTC, neobelov commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +                List<Integer> user_ids = converter.convert(rs.getArray("user_ids"));
Принято

2023-01-27 13:53 UTC, neobelov commented on src/main/java/ru/yandex/practicum/filmorate/utilities/recommendations/Matrix.java
> +        }
Исправил

2023-01-27 13:54 UTC, neobelov commented on src/main/java/ru/yandex/practicum/filmorate/utilities/recommendations/Recommender.java
> +            return List.of();
Принято

2023-01-27 14:27 UTC, smdka approved these changes

2023-01-28 16:00 UTC, zvrzhina commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
>          this.storage = storage;
(минор) если мы ввели this.filmStorage = filmStorage, то может быть стоит тогда сделать Refactor -> rename для UserStorage storage на userStorage

2023-01-28 16:05 UTC, zvrzhina commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +                        "ARRAY_AGG(fl.liked_by_user_id/fl.liked_by_user_id) rates " +
Не понимаю эту строчку "ARRAY_AGG(fl.liked_by_user_id/fl.liked_by_user_id)
можешь пожалуйста пояснить что будет в столбце?

2023-01-28 16:13 UTC, zvrzhina commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        Recommender recommender = new Recommender(matrix);
Если matrix = null, то взорвемся?

2023-01-28 16:24 UTC, zvrzhina requested changes
Я готова ставить апрув, только добавь пожалуйста тесты

2023-01-28 20:44 UTC, neobelov commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +                        "ARRAY_AGG(fl.liked_by_user_id/fl.liked_by_user_id) rates " +
Здесь просто подготовлено уже к рефактору лайков в оценки, эта строка получает массив рейтингов, которые пока равны единице 
Когда будут оценки, сюда подставим уже ссылку на столбец рейтингов

2023-01-28 20:45 UTC, neobelov commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
>          this.storage = storage;
Просто, я опасаюсь конфликтов с основной веткой, у всех же не так написано)

2023-01-28 20:46 UTC, neobelov commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
>          this.storage = storage;
Но можно, да, переделать

2023-01-29 06:34 UTC, neobelov commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        Recommender recommender = new Recommender(matrix);
Спасибо, добавил проверку.

2023-01-29 08:33 UTC, neobelov commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
>          this.storage = storage;
Сделал

2023-01-29 18:14 UTC, zvrzhina approved these changes

2023-01-29 18:20 UTC, merged