Функциональность "Общие фильмы"
smdka/java-filmorate pull request #17
Opened 2023-01-26 21:25 UTC by smdka

2023-01-27 17:56 UTC, zvrzhina commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public Collection<Film> getCommonFilms(int userId, int friendId) {
Нужна ли нам проверка что friendId действительно друг userId?
Типа что метод не может быть использован для "не друзей"

2023-01-27 18:00 UTC, smdka commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public Collection<Film> getCommonFilms(int userId, int friendId) {
Да, согласен. Невнимательно прочитал описание. Действительно общие фильмы только для друзей

2023-01-27 18:15 UTC, zvrzhina commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +                                film.getWhoLikedUserIds().contains(friendId))
Я не очень сильна в лямбдах, но здесь разве точно выведет отсортированных по популярности? .sorted(Comparator.comparingInt(Film::getId).reversed())

2023-01-27 18:17 UTC, smdka commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +                                film.getWhoLikedUserIds().contains(friendId))
Разумеется нет 😂 поправлю

2023-01-27 18:17 UTC, zvrzhina reviewed
Понятный код, осталось покрыть одно требование

2023-01-28 21:29 UTC, smdka commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public Collection<Film> getCommonFilms(int userId, int friendId) {
Не поправил, так как в тестах Postman дружба не учитывается

2023-01-28 21:29 UTC, smdka commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +                                film.getWhoLikedUserIds().contains(friendId))
Поправил

2023-01-28 22:33 UTC, ErikManv approved these changes

2023-01-29 06:35 UTC, avbekker requested changes

2023-01-29 06:35 UTC, avbekker commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +        if (sortBy.equals("year")) {
Возможно тут лучше использовать switch case с использованием default для обработки ошибок, либо добавить еще один else для обработки вариантов с неправильным sortBy (например могут ввести Year, YEAR и тд.)

2023-01-29 12:50 UTC, smdka commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +        if (sortBy.equals("year")) {
Поправил

2023-01-29 13:26 UTC, avbekker approved these changes

2023-01-29 13:28 UTC, merged