Add feed
smdka/java-filmorate pull request #18
Opened 2023-01-28 11:00 UTC by avbekker

2023-01-29 13:09 UTC, smdka commented on src/main/java/ru/yandex/practicum/filmorate/model/Feed.java
> +    @NotBlank
NotBlank применяется к строкам. И лучше вставлять пустые строки между аннотациями

2023-01-29 13:09 UTC, smdka commented on src/main/java/ru/yandex/practicum/filmorate/model/Feed.java
> +    @NotBlank
Тоже самое

2023-01-29 13:09 UTC, smdka commented on src/main/java/ru/yandex/practicum/filmorate/model/Feed.java
> +    @NotBlank
Тоже самое

2023-01-29 13:09 UTC, smdka commented on src/main/java/ru/yandex/practicum/filmorate/model/Feed.java
> +    @NotBlank
Тоже самое

2023-01-29 13:09 UTC, smdka commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        log.debug("Лента новостей для пользователя с id = {} отправлен", id);
"Отправлена", опечатка

2023-01-29 13:09 UTC, smdka commented on src/main/java/ru/yandex/practicum/filmorate/storage/review/ReviewDbStorage.java
> +        } catch (EmptyResultDataAccessException e) {
Лучше не ловить исключение. Лучше использовать примитивный тип для filmId, там может быть null. Если удаление успешное ( >0), вставляем событие и возвращаем true, в противном случае возвращаем false

2023-01-29 13:09 UTC, smdka commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDdStorage.java
> +        jdbcTemplate.update(ADD_FEED,
Если удаление друга не удастся, событие все равно запишется?

2023-01-29 13:09 UTC, smdka commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDdStorage.java
> +        //String sql = "SELECT * FROM USER_FEEDS WHERE USER_ID = ?";
Закомментированный код лучше убрать

2023-01-29 13:11 UTC, smdka requested changes
Все хорошо, надо внести немного изменений и добавить тесты

2023-01-29 20:07 UTC, zvrzhina commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +    @Override
Мне кажется @Override стоит убрать, поскольку класс больше не имплементирует общий  с db интерфейс

2023-01-29 20:18 UTC, zvrzhina commented on src/main/java/ru/yandex/practicum/filmorate/model/Feed.java
> +    private String eventType;
Я видела ты добавил enum на уровень бд и это правильно. Никто "грязными руками не сможет" заинсертить что-то кривое в базу. Но мне кажется следует добавить такую же валидацию для eventType и operation на уровне контроллера, чтобы отсекать неподдерживаемые реквесты сразу же при получении некорректного запроса. Подробнее здесь https://www.baeldung.com/spring-enum-request-param

2023-01-29 20:26 UTC, zvrzhina commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +                userId, Instant.now().toEpochMilli(), "LIKE", "ADD", filmId);
Почему в toEpochMilli(), а не в  toEpochSecond()?
В задании был пример "timestamp": 123344556 и я пропустила через https://www.epochconverter.com/ . Он предполагает что речь о секундах.

2023-01-30 15:52 UTC, avbekker commented on src/main/java/ru/yandex/practicum/filmorate/model/Feed.java
> +    @NotBlank
fixed

2023-01-30 15:53 UTC, avbekker commented on src/main/java/ru/yandex/practicum/filmorate/model/Feed.java
> +    @NotBlank
fixed

2023-01-30 15:55 UTC, avbekker commented on src/main/java/ru/yandex/practicum/filmorate/model/Feed.java
> +    @NotBlank
тут строка, стоит ли менять на нотнул?

2023-01-30 15:55 UTC, avbekker commented on src/main/java/ru/yandex/practicum/filmorate/model/Feed.java
> +    @NotBlank
исправил

2023-01-30 15:57 UTC, avbekker commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        log.debug("Лента новостей для пользователя с id = {} отправлен", id);
исправил

2023-01-30 16:09 UTC, smdka commented on src/main/java/ru/yandex/practicum/filmorate/model/Feed.java
> +    @NotBlank
Нет, я думал я убрал этот коммент :)

2023-01-30 16:18 UTC, avbekker commented on src/main/java/ru/yandex/practicum/filmorate/storage/review/ReviewDbStorage.java
> +        } catch (EmptyResultDataAccessException e) {
убрал try-catch, добавил проверку на null для filmId, думаю так будет надежнее

2023-01-30 16:20 UTC, avbekker commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDdStorage.java
> +        jdbcTemplate.update(ADD_FEED,
fixed

2023-01-30 16:21 UTC, avbekker commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDdStorage.java
> +        //String sql = "SELECT * FROM USER_FEEDS WHERE USER_ID = ?";
забыл про него) удалил

2023-01-30 16:26 UTC, avbekker commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +                userId, Instant.now().toEpochMilli(), "LIKE", "ADD", filmId);
цифры в примере - просто случайный набор, тесты в постмане сверяют именно миллисекунды

2023-01-30 16:35 UTC, avbekker commented on src/main/java/ru/yandex/practicum/filmorate/model/Feed.java
> +    private String eventType;
с запросами не приходят эти данные, могу в принципе создать доп классы enum для этих строк, но большой разницы не будет, тк эти запросы пишутся только внутри метода без данных извне

2023-01-30 16:42 UTC, avbekker commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +    @Override
вот тут загвоздка, интерфейс у них общий. Я и думал, что стоит наверное сделать реализацию и для этого класса, но получится без отзывов. По этому поводу на Q&A сказали можно использовать заглушку - как пока что у меня. А если убирать метод из интерфейса - проблемы с сервисом, тк он использует для хранилища интерфейс UserStorage. Может дождемся комментария ревьюера по этой проблеме?

2023-01-30 17:44 UTC, smdka commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +    @Override
Лучше все-таки делать заглушки

2023-01-30 18:10 UTC, smdka approved these changes

2023-01-30 18:14 UTC, zvrzhina approved these changes

2023-01-30 18:16 UTC, merged