Добавлен поиск по режиссерам и названиям фильмов.
smdka/java-filmorate pull request #19
Opened 2023-01-28 13:26 UTC by Victorioussword

2023-01-30 07:12 UTC, smdka requested changes
Необходимо поправить ряд моментов. Кроме того, нет тестов

2023-01-30 07:12 UTC, smdka commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmsController.java
> +        if (query == null || by == null || query.isEmpty() || by.isEmpty()) {
Проверку можно упростить. Заодно  можно почитать про мульти-параметры как by. Кроме того, я бы рассмотрел использование Enum
https://www.baeldung.com/spring-request-param
https://www.baeldung.com/spring-enum-request-param

2023-01-30 07:12 UTC, smdka commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmsController.java
> +            throw new ValidationException("Не корректный запрос на поиск");
Это некорректное исключение, так как оно бросается при невалидности передаваемой модели (Film, User, Review и тд)

2023-01-30 07:12 UTC, smdka commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmsController.java
> +        List<Film> filmsForReturn = filmService.searchFilm(query, by);
Можно не создавать промежуточную переменную и сразу возвращать filmService.searchFilm(), который я бы переименовал в searchForFilms или как-то, так как мы ищем не один фильм, а все возможные.

2023-01-30 07:12 UTC, smdka commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        String byLow = "%" + query.toLowerCase() + "%";
Тут есть опасность реализовать sql injection. Кроме того, можно использовать оператор ILIKE, который выполняет регистро-независимый поиск

2023-01-30 07:12 UTC, smdka commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +            return forReturn;
можно просто написать return Collections.emptyList();

2023-01-30 14:02 UTC, ErikManv commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmsController.java
> +            throw new ValidationException("Не корректный запрос на поиск");
Ты можешь подсмотреть, реализацию getFilmsByDirector. Там я столкнулся с похожей ситуацией и по совету Ильи реализовал через enum

2023-01-30 18:34 UTC, neobelov commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmsController.java
>              throw new RuntimeException("неверный запрос параметра сортировки");
Правильнее использовать свое исключение, а не стандартное, это считается хорошей практикой, насколько мне известно.

2023-01-30 18:36 UTC, smdka commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmsController.java
>              throw new RuntimeException("неверный запрос параметра сортировки");
> Правильнее использовать свое исключение, а не стандартное, это считается хорошей практикой, насколько мне известно.

Это другой функционал. Не поиск

2023-01-30 18:43 UTC, neobelov commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        if (by.equals("director")) {
Лучше использовать оператор switch и default

2023-01-30 18:45 UTC, neobelov commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +            List<Film> filmsForReturn = jdbcTemplate.query(sql, (rs, rowNum) -> mapRowToFilm(rs), byLow);
Промежуточную переменную здесь и далее можно не создавать

2023-01-30 18:46 UTC, neobelov requested changes
Привет:) работа хорошая) в основном, Илья отписал все, что нужно поправить, от меня небольшие комментарии

2023-01-30 20:02 UTC, smdka requested changes

2023-01-30 20:02 UTC, smdka commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        } else if (by.equals("title,director")) {
А что будет если строчка будет "director,title"?

2023-01-31 13:39 UTC, smdka approved these changes

2023-01-31 13:55 UTC, neobelov approved these changes

2023-01-31 13:57 UTC, merged